#!/bin/bash

if [ -f "$PWD/2done" ]; then
sudo deluser temp
sudo rm -r /home/temp
sudo apt purge iptables -y
sudo rm -r /etc/iptables
sudo apt install ufw -y
curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
sudo apt-get update
sudo apt-get install tailscale -y
sudo tailscale up
sudo ufw enable
sudo ufw allow in on tailscale0 proto tcp from any to any port 22
sudo ufw reload
sudo timedatectl set-timezone Europe/Budapest
echo "Kész van minden! Újraindítás 3 másodperc múlva!"
sleep 3
sudo reboot

	else
sudo apt update && sudo apt upgrade -y
sudo mkdir /home/temp
sudo adduser temp
sudo adduser temp sudo
sudo mkdir /home/temp/.ssh
sudo chown temp:temp /home/temp/.ssh
sudo chmod 700 /home/temp/.ssh
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMmyylNd1Rgd19ZVwaaTPmcVlhP8uRWGXy0XPeJ8hkGkVTr5uY2loLbtQab8Az2S3v76d6f/90+IQrvpGnXpui+JLmnDsfBXRaOWaPrRpri65FRjPtun6PyVstGfNfd0LKEEpqZprM2UWVFet+IrIH7DusQFJm8cLXFmFztShe/sF11oJ6aAtnz5iq/tL9CS+1dDR4P+cdY4qisn4eVxFvTGgO6VnH051uJCd33/57L9a9f1rBQ31g6l+1mjzxu8cH1tkt17dJM/vVyHE/WxSgDfaNs+RdIN2O4CGG0OoGT8GAjXCjxvs8htn0h1k011Bhjh364EkKeq0772/cBcY5 Generated By Termius" | sudo tee /home/temp/.ssh/authorized_keys
sudo chown temp:temp /home/temp/.ssh/authorized_keys
sudo chmod 600 /home/temp/.ssh/authorized_keys
sudo wget https://raw.githubusercontent.com/BanicTibor/source/main/script/firstsetup/2script.sh -O /home/temp/2script.sh
sudo chmod 700 /home/temp/2script.sh
sudo chown temp:temp /home/temp/2script.sh
echo "Első rész kész! Lépj át az ideiglenes felhasználódba és futtasd az ott lévő szkriptet!"
fi